// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjhIc-h56VzqCJ0axntUk8SWtyAY6i2eY',
    appId: '1:150336899991:web:1552b3dcc56f7ed2f512d2',
    messagingSenderId: '150336899991',
    projectId: 'resqconnect-prod',
    authDomain: 'resqconnect-prod.firebaseapp.com',
    storageBucket: 'resqconnect-prod.firebasestorage.app',
    measurementId: 'G-9F6G17M19S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1ZvUdVZoBSEQb2kaUUtWzimVUd6HQedU',
    appId: '1:150336899991:android:d9d3e6f79890c690f512d2',
    messagingSenderId: '150336899991',
    projectId: 'resqconnect-prod',
    storageBucket: 'resqconnect-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA6uS2J5VQqsFJcLovQdK2G-MmTdek76I',
    appId: '1:150336899991:ios:f309623f2f1949d2f512d2',
    messagingSenderId: '150336899991',
    projectId: 'resqconnect-prod',
    storageBucket: 'resqconnect-prod.firebasestorage.app',
    iosClientId: '150336899991-2heua5h669kiuaqqfh8lov7ll6l5fptf.apps.googleusercontent.com',
    iosBundleId: 'com.example.resqConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA6uS2J5VQqsFJcLovQdK2G-MmTdek76I',
    appId: '1:150336899991:ios:f309623f2f1949d2f512d2',
    messagingSenderId: '150336899991',
    projectId: 'resqconnect-prod',
    storageBucket: 'resqconnect-prod.firebasestorage.app',
    iosClientId: '150336899991-2heua5h669kiuaqqfh8lov7ll6l5fptf.apps.googleusercontent.com',
    iosBundleId: 'com.example.resqConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjhIc-h56VzqCJ0axntUk8SWtyAY6i2eY',
    appId: '1:150336899991:web:fce1da7878e13de1f512d2',
    messagingSenderId: '150336899991',
    projectId: 'resqconnect-prod',
    authDomain: 'resqconnect-prod.firebaseapp.com',
    storageBucket: 'resqconnect-prod.firebasestorage.app',
    measurementId: 'G-TPEZPNQKY3',
  );
}
