import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:firebase_auth/firebase_auth.dart' hide AuthProvider;
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:image_picker/image_picker.dart';
import 'package:provider/provider.dart';

import '../../providers/auth_provider.dart';
import '../../widgets/loading_overlay.dart';
import 'otp_verification_screen.dart';

// ─── Philippine Provinces & Cities Data ──────────────────────────────────────

const Map<String, List<String>> _phProvinceCities = {
  'Metro Manila (NCR)': [
    'Caloocan',
    'Las Piñas',
    'Makati',
    'Malabon',
    'Mandaluyong',
    'Manila',
    'Marikina',
    'Muntinlupa',
    'Navotas',
    'Parañaque',
    'Pasay',
    'Pasig',
    'Pateros',
    'Quezon City',
    'San Juan',
    'Taguig',
    'Valenzuela',
  ],
  'Abra': [
    'Bangued',
    'Boliney',
    'Bucay',
    'Bucloc',
    'Daguioman',
    'Danglas',
    'Dolores',
    'La Paz',
    'Lacub',
    'Lagangilang',
    'Lagayan',
    'Langiden',
    'Licuan-Baay',
    'Luba',
    'Malibcong',
    'Manabo',
    'Peñarrubia',
    'Pidigan',
    'Pilar',
    'Sallapadan',
    'San Isidro',
    'San Juan',
    'San Quintin',
    'Tayum',
    'Tineg',
    'Tubo',
    'Villaviciosa',
  ],
  'Agusan del Norte': [
    'Butuan City',
    'Cabadbaran City',
    'Buenavista',
    'Carmen',
    'Jabonga',
    'Kitcharao',
    'Las Nieves',
    'Magallanes',
    'Nasipit',
    'Remedios T. Romualdez',
    'Santiago',
    'Tubay',
  ],
  'Agusan del Sur': [
    'Bayugan City',
    'Bunawan',
    'Esperanza',
    'La Paz',
    'Loreto',
    'Prosperidad',
    'Rosario',
    'San Francisco',
    'San Luis',
    'Santa Josefa',
    'Sibagat',
    'Talacogon',
    'Trento',
    'Veruela',
  ],
  'Aklan': [
    'Altavas',
    'Balete',
    'Banga',
    'Batan',
    'Buruanga',
    'Ibajay',
    'Kalibo',
    'Lezo',
    'Libacao',
    'Madalag',
    'Makato',
    'Malay',
    'Malinao',
    'Nabas',
    'New Washington',
    'Numancia',
    'Tangalan',
  ],
  'Albay': [
    'Legazpi City',
    'Ligao City',
    'Tabaco City',
    'Bacacay',
    'Camalig',
    'Daraga',
    'Guinobatan',
    'Jovellar',
    'Libon',
    'Malilipot',
    'Malinao',
    'Manito',
    'Oas',
    'Pio Duran',
    'Polangui',
    'Rapu-Rapu',
    'Santo Domingo',
    'Tiwi',
  ],
  'Antique': [
    'San Jose de Buenavista',
    'Anini-y',
    'Barbaza',
    'Belison',
    'Bugasong',
    'Caluya',
    'Culasi',
    'Hamtic',
    'Laua-an',
    'Libertad',
    'Pandan',
    'Patnongon',
    'San Remigio',
    'Sebaste',
    'Sibalom',
    'Tibiao',
    'Tobias Fornier',
    'Valderrama',
  ],
  'Apayao': [
    'Calanasan',
    'Conner',
    'Flora',
    'Kabugao',
    'Luna',
    'Pudtol',
    'Santa Marcela',
  ],
  'Aurora': [
    'Baler',
    'Casiguran',
    'Dilasag',
    'Dinalungan',
    'Dingalan',
    'Dipaculao',
    'Maria Aurora',
    'San Luis',
  ],
  'Basilan': [
    'Isabela City',
    'Lamitan City',
    'Akbar',
    'Al-Barka',
    'Hadji Mohammad Ajul',
    'Hadji Muhtamad',
    'Lantawan',
    'Maluso',
    'Sumisip',
    'Tipo-Tipo',
    'Tuburan',
    'Ungkaya Pukan',
  ],
  'Bataan': [
    'Balanga City',
    'Abucay',
    'Bagac',
    'Dinalupihan',
    'Hermosa',
    'Limay',
    'Mariveles',
    'Morong',
    'Orani',
    'Orion',
    'Pilar',
    'Samal',
  ],
  'Batanes': ['Basco', 'Itbayat', 'Ivana', 'Mahatao', 'Sabtang', 'Uyugan'],
  'Batangas': [
    'Batangas City',
    'Lipa City',
    'Tanauan City',
    'Agoncillo',
    'Alitagtag',
    'Balayan',
    'Balete',
    'Banay-Banay',
    'Bauan',
    'Calaca',
    'Calatagan',
    'Cuenca',
    'Ibaan',
    'Laurel',
    'Lemery',
    'Lian',
    'Lobo',
    'Mabini',
    'Malvar',
    'Mataas na Kahoy',
    'Nasugbu',
    'Padre Garcia',
    'Rosario',
    'San Jose',
    'San Juan',
    'San Luis',
    'San Nicolas',
    'San Pascual',
    'Santa Teresita',
    'Santo Tomas',
    'Taal',
    'Talisay',
    'Taysan',
    'Tingloy',
    'Tuy',
  ],
  'Benguet': [
    'Baguio City',
    'Atok',
    'Bakun',
    'Bokod',
    'Buguias',
    'Itogon',
    'Kabayan',
    'Kibungan',
    'La Trinidad',
    'Mankayan',
    'Sablan',
    'Tuba',
    'Tublay',
  ],
  'Biliran': [
    'Naval',
    'Almeria',
    'Biliran',
    'Cabucgayan',
    'Caibiran',
    'Culaba',
    'Kawayan',
    'Maripipi',
  ],
  'Bohol': [
    'Tagbilaran City',
    'Alburquerque',
    'Alicia',
    'Anda',
    'Antequera',
    'Baclayon',
    'Balilihan',
    'Batuan',
    'Bien Unido',
    'Bilar',
    'Buenavista',
    'Calape',
    'Candijay',
    'Carmen',
    'Catigbian',
    'Clarin',
    'Corella',
    'Cortes',
    'Dagohoy',
    'Danao',
    'Dauis',
    'Dimiao',
    'Duero',
    'Garcia Hernandez',
    'Getafe',
    'Guindulman',
    'Inabanga',
    'Jagna',
    'Lila',
    'Loay',
    'Loboc',
    'Loon',
    'Mabini',
    'Maribojoc',
    'Panglao',
    'Pilar',
    'Pres. Carlos P. Garcia',
    'Sagbayan',
    'San Isidro',
    'San Miguel',
    'Sevilla',
    'Sierra Bullones',
    'Sikatuna',
    'Talibon',
    'Trinidad',
    'Tubigon',
    'Ubay',
    'Valencia',
  ],
  'Bukidnon': [
    'Malaybalay City',
    'Valencia City',
    'Baungon',
    'Cabanglasan',
    'Damulog',
    'Dangcagan',
    'Don Carlos',
    'Impasugong',
    'Kadingilan',
    'Kalilangan',
    'Kibawe',
    'Kitaotao',
    'Lantapan',
    'Libona',
    'Malitbog',
    'Manolo Fortich',
    'Maramag',
    'Pangantucan',
    'Quezon',
    'San Fernando',
    'Sumilao',
    'Talakag',
  ],
  'Bulacan': [
    'Malolos City',
    'Meycauayan City',
    'San Jose del Monte City',
    'Angat',
    'Balagtas',
    'Baliuag',
    'Bocaue',
    'Bulakan',
    'Bustos',
    'Calumpit',
    'Doña Remedios Trinidad',
    'Guiguinto',
    'Hagonoy',
    'Marilao',
    'Norzagaray',
    'Obando',
    'Pandi',
    'Paombong',
    'Plaridel',
    'Pulilan',
    'San Ildefonso',
    'San Miguel',
    'San Rafael',
    'Santa Maria',
  ],
  'Cagayan': [
    'Tuguegarao City',
    'Abulug',
    'Alcala',
    'Allacapan',
    'Amulung',
    'Aparri',
    'Baggao',
    'Ballesteros',
    'Buguey',
    'Calayan',
    'Camalaniugan',
    'Claveria',
    'Enrile',
    'Gattaran',
    'Gonzaga',
    'Iguig',
    'Lal-lo',
    'Lasam',
    'Pamplona',
    'Peñablanca',
    'Piat',
    'Rizal',
    'Sanchez-Mira',
    'Santa Ana',
    'Santa Praxedes',
    'Santa Teresita',
    'Santo Niño',
    'Solana',
    'Tuao',
  ],
  'Camarines Norte': [
    'Daet',
    'Basud',
    'Capalonga',
    'Jose Panganiban',
    'Labo',
    'Mercedes',
    'Paracale',
    'San Lorenzo Ruiz',
    'San Vicente',
    'Santa Elena',
    'Talisay',
    'Vinzons',
  ],
  'Camarines Sur': [
    'Iriga City',
    'Naga City',
    'Baao',
    'Balatan',
    'Bato',
    'Bombon',
    'Buhi',
    'Bula',
    'Cabusao',
    'Calabanga',
    'Camaligan',
    'Canaman',
    'Caramoan',
    'Del Gallego',
    'Gainza',
    'Garchitorena',
    'Goa',
    'Lagonoy',
    'Libmanan',
    'Lupi',
    'Magarao',
    'Milaor',
    'Minalabac',
    'Nabua',
    'Ocampo',
    'Pamplona',
    'Pasacao',
    'Pili',
    'Presentacion',
    'Ragay',
    'Sagñay',
    'San Fernando',
    'San Jose',
    'Sipocot',
    'Siruma',
    'Tigaon',
    'Tinambac',
  ],
  'Camiguin': ['Mambajao', 'Catarman', 'Guinsiliban', 'Mahinog', 'Sagay'],
  'Capiz': [
    'Roxas City',
    'Cuartero',
    'Dao',
    'Dumalag',
    'Dumarao',
    'Ivisan',
    'Jamindan',
    'Maayon',
    'Mambusao',
    'Panay',
    'Panitan',
    'Pilar',
    'Pontevedra',
    'President Roxas',
    'Sapian',
    'Sigma',
    'Tapaz',
  ],
  'Catanduanes': [
    'Virac',
    'Bagamanoc',
    'Baras',
    'Bato',
    'Caramoran',
    'Gigmoto',
    'Pandan',
    'Panganiban',
    'San Andres',
    'San Miguel',
    'Viga',
  ],
  'Cavite': [
    'Bacoor City',
    'Cavite City',
    'Dasmariñas City',
    'General Trias City',
    'Imus City',
    'Tagaytay City',
    'Trece Martires City',
    'Alfonso',
    'Amadeo',
    'Carmona',
    'General Emilio Aguinaldo',
    'General Mariano Alvarez',
    'Indang',
    'Kawit',
    'Magallanes',
    'Maragondon',
    'Mendez',
    'Naic',
    'Noveleta',
    'Rosario',
    'Silang',
    'Tanza',
    'Ternate',
  ],
  'Cebu': [
    'Cebu City',
    'Danao City',
    'Lapu-Lapu City',
    'Mandaue City',
    'Naga City',
    'Talisay City',
    'Toledo City',
    'Alcantara',
    'Alcoy',
    'Alegria',
    'Aloguinsan',
    'Argao',
    'Asturias',
    'Badian',
    'Balamban',
    'Bantayan',
    'Barili',
    'Bogo City',
    'Boljoon',
    'Borbon',
    'Carmen',
    'Catmon',
    'Compostela',
    'Consolacion',
    'Cordova',
    'Daanbantayan',
    'Dalaguete',
    'Dumanjug',
    'Ginatilan',
    'Liloan',
    'Madridejos',
    'Malabuyoc',
    'Medellin',
    'Minglanilla',
    'Moalboal',
    'Oslob',
    'Pilar',
    'Pinamungahan',
    'Poro',
    'Ronda',
    'Samboan',
    'San Fernando',
    'San Francisco',
    'San Remigio',
    'Santa Fe',
    'Santander',
    'Sibonga',
    'Sogod',
    'Tabogon',
    'Tabuelan',
    'Tuburan',
    'Tudela',
  ],
  'Compostela Valley': [
    'Nabunturan',
    'Compostela',
    'Laak',
    'Mabini',
    'Maco',
    'Maragusan',
    'Mawab',
    'Monkayo',
    'Montevista',
    'New Bataan',
    'Pantukan',
  ],
  'Cotabato': [
    'Kidapawan City',
    'Alamada',
    'Aleosan',
    'Antipas',
    'Arakan',
    'Banisilan',
    'Carmen',
    'Kabacan',
    'Libungan',
    'Magpet',
    'Makilala',
    'Matalam',
    'Midsayap',
    'Mlang',
    'Pigkawayan',
    'Pikit',
    'President Roxas',
    'Tulunan',
  ],
  'Davao de Oro': [
    'Nabunturan',
    'Compostela',
    'Laak',
    'Mabini',
    'Maco',
    'Maragusan',
    'Mawab',
    'Monkayo',
    'Montevista',
    'New Bataan',
    'Pantukan',
  ],
  'Davao del Norte': [
    'Tagum City',
    'Panabo City',
    'Island Garden City of Samal',
    'Asuncion',
    'Braulio E. Dujali',
    'Carmen',
    'Kapalong',
    'New Corella',
    'San Isidro',
    'Santo Tomas',
    'Talaingod',
  ],
  'Davao del Sur': [
    'Davao City',
    'Digos City',
    'Bansalan',
    'Don Marcelino',
    'Hagonoy',
    'Jose Abad Santos',
    'Kiblawan',
    'Magsaysay',
    'Malalag',
    'Malita',
    'Matanao',
    'Padada',
    'Santa Cruz',
    'Santa Maria',
    'Sulop',
  ],
  'Davao Occidental': [
    'Malita',
    'Don Marcelino',
    'Jose Abad Santos',
    'Santa Maria',
    'Sarangani',
  ],
  'Davao Oriental': [
    'Mati City',
    'Baganga',
    'Banaybanay',
    'Boston',
    'Caraga',
    'Cateel',
    'Governor Generoso',
    'Lupon',
    'Manay',
    'San Isidro',
    'Tarragona',
  ],
  'Dinagat Islands': [
    'San Jose',
    'Basilisa',
    'Cagdianao',
    'Dinagat',
    'Libjo',
    'Loreto',
    'Tubajon',
  ],
  'Eastern Samar': [
    'Borongan City',
    'Arteche',
    'Balangiga',
    'Balangkayan',
    'Can-avid',
    'Dolores',
    'General MacArthur',
    'Giporlos',
    'Guiuan',
    'Hernani',
    'Jipapad',
    'Lawaan',
    'Llorente',
    'Maslog',
    'Maydolong',
    'Mercedes',
    'Oras',
    'Quinapondan',
    'Salcedo',
    'San Julian',
    'San Policarpo',
    'Sulat',
    'Taft',
  ],
  'Guimaras': [
    'Jordan',
    'Buenavista',
    'Nueva Valencia',
    'San Lorenzo',
    'Sibunag',
  ],
  'Ifugao': [
    'Lagawe',
    'Alfonso Lista',
    'Asipulo',
    'Banaue',
    'Hingyon',
    'Hungduan',
    'Kiangan',
    'Lamut',
    'Mayoyao',
    'Tinoc',
  ],
  'Ilocos Norte': [
    'Laoag City',
    'Batac City',
    'Adams',
    'Bacarra',
    'Badoc',
    'Bangui',
    'Banna',
    'Burgos',
    'Carasi',
    'Currimao',
    'Dingras',
    'Dumalneg',
    'Marcos',
    'Nueva Era',
    'Pagudpud',
    'Paoay',
    'Pasuquin',
    'Piddig',
    'Pinili',
    'San Nicolas',
    'Sarrat',
    'Solsona',
    'Vintar',
  ],
  'Ilocos Sur': [
    'Vigan City',
    'Candon City',
    'Alilem',
    'Banayoyo',
    'Bantay',
    'Burgos',
    'Cabugao',
    'Caoayan',
    'Cervantes',
    'Galimuyod',
    'Gregorio del Pilar',
    'Lidlidda',
    'Magsingal',
    'Nagbukel',
    'Narvacan',
    'Quirino',
    'Salcedo',
    'San Emilio',
    'San Esteban',
    'San Ildefonso',
    'San Juan',
    'San Vicente',
    'Santa',
    'Santa Catalina',
    'Santa Cruz',
    'Santa Lucia',
    'Santa Maria',
    'Santiago',
    'Sigay',
    'Sinait',
    'Sugpon',
    'Suyo',
    'Tagudin',
  ],
  'Iloilo': [
    'Iloilo City',
    'Passi City',
    'Ajuy',
    'Alimodian',
    'Anilao',
    'Badiangan',
    'Balasan',
    'Banate',
    'Barotac Nuevo',
    'Barotac Viejo',
    'Batad',
    'Bingawan',
    'Cabatuan',
    'Calinog',
    'Carles',
    'Concepcion',
    'Dingle',
    'Dueñas',
    'Dumangas',
    'Estancia',
    'Guimbal',
    'Igbaras',
    'Janiuay',
    'Lambunao',
    'Leganes',
    'Lemery',
    'Leon',
    'Maasin',
    'Miagao',
    'Mina',
    'New Lucena',
    'Oton',
    'Pavia',
    'Pototan',
    'San Dionisio',
    'San Enrique',
    'San Joaquin',
    'San Miguel',
    'San Rafael',
    'Santa Barbara',
    'Sara',
    'Tigbauan',
    'Tubungan',
    'Zarraga',
  ],
  'Isabela': [
    'Cauayan City',
    'Ilagan City',
    'Santiago City',
    'Alicia',
    'Angadanan',
    'Aurora',
    'Benito Soliven',
    'Burgos',
    'Cabagan',
    'Cabatuan',
    'Cordon',
    'Delfin Albano',
    'Dinapigue',
    'Divilacan',
    'Echague',
    'Gamu',
    'Jones',
    'Luna',
    'Maconacon',
    'Mallig',
    'Naguilian',
    'Palanan',
    'Quezon',
    'Quirino',
    'Ramon',
    'Reina Mercedes',
    'Roxas',
    'San Agustin',
    'San Guillermo',
    'San Isidro',
    'San Manuel',
    'San Mariano',
    'San Mateo',
    'San Pablo',
    'Santa Maria',
    'Santo Tomas',
    'Tumauini',
  ],
  'Kalinga': [
    'Tabuk City',
    'Balbalan',
    'Lubuagan',
    'Pasil',
    'Pinukpuk',
    'Rizal',
    'Tanudan',
    'Tinglayan',
  ],
  'La Union': [
    'San Fernando City',
    'Agoo',
    'Aringay',
    'Bacnotan',
    'Bagulin',
    'Balaoan',
    'Bangar',
    'Bauang',
    'Burgos',
    'Caba',
    'Luna',
    'Naguilian',
    'Pugo',
    'Rosario',
    'San Gabriel',
    'San Juan',
    'Santo Tomas',
    'Santol',
    'Sudipen',
    'Tubao',
  ],
  'Laguna': [
    'Calamba City',
    'San Pablo City',
    'Santa Rosa City',
    'Alaminos',
    'Bay',
    'Biñan City',
    'Cabuyao City',
    'Cavinti',
    'Famy',
    'Kalayaan',
    'Liliw',
    'Los Baños',
    'Luisiana',
    'Lumban',
    'Mabitac',
    'Magdalena',
    'Majayjay',
    'Nagcarlan',
    'Pagsanjan',
    'Pakil',
    'Pangil',
    'Pila',
    'Rizal',
    'San Pedro City',
    'Santa Cruz',
    'Santa Maria',
    'Siniloan',
    'Victoria',
  ],
  'Lanao del Norte': [
    'Iligan City',
    'Bacolod',
    'Baloi',
    'Baroy',
    'Kapatagan',
    'Kauswagan',
    'Kolambugan',
    'Lala',
    'Linamon',
    'Magsaysay',
    'Maigo',
    'Matungao',
    'Munai',
    'Nunungan',
    'Pantao Ragat',
    'Pantar',
    'Poona Piagapo',
    'Salvador',
    'Sapad',
    'Sultan Naga Dimaporo',
    'Tagoloan',
    'Tangcal',
    'Tubod',
  ],
  'Lanao del Sur': [
    'Marawi City',
    'Bacolod-Kalawi',
    'Balabagan',
    'Balindong',
    'Bayang',
    'Binidayan',
    'Buadiposo-Buntong',
    'Bubong',
    'Bumbaran',
    'Butig',
    'Calanogas',
    'Ditsaan-Ramain',
    'Ganassi',
    'Kapai',
    'Kapatagan',
    'Lumba-Bayabao',
    'Lumbaca-Unayan',
    'Lumbatan',
    'Lumbayanague',
    'Madalum',
    'Madamba',
    'Maguing',
    'Malabang',
    'Marantao',
    'Marogong',
    'Masiu',
    'Mulondo',
    'Pagayawan',
    'Piagapo',
    'Picong',
    'Poona Bayabao',
    'Pualas',
    'Saguiaran',
    'Sultan Dumalondong',
    'Tagoloan II',
    'Tamparan',
    'Taraka',
    'Tubaran',
    'Tugaya',
    'Wao',
  ],
  'Leyte': [
    'Tacloban City',
    'Ormoc City',
    'Abuyog',
    'Alangalang',
    'Albuera',
    'Babatngon',
    'Barugo',
    'Bato',
    'Baybay City',
    'Burauen',
    'Calubian',
    'Capoocan',
    'Carigara',
    'Dagami',
    'Dulag',
    'Hilongos',
    'Hindang',
    'Inopacan',
    'Isabel',
    'Jaro',
    'Javier',
    'Julita',
    'Kananga',
    'La Paz',
    'Leyte',
    'MacArthur',
    'Mahaplag',
    'Matag-ob',
    'Matalom',
    'Mayorga',
    'Merida',
    'Palo',
    'Palompon',
    'Pastrana',
    'San Isidro',
    'San Miguel',
    'Santa Fe',
    'Tabango',
    'Tabontabon',
    'Tanauan',
    'Tolosa',
    'Tunga',
    'Villaba',
  ],
  'Maguindanao': [
    'Cotabato City',
    'Buluan',
    'Datu Abdullah Sangki',
    'Datu Anggal Midtimbang',
    'Datu Blah T. Sinsuat',
    'Datu Hoffer Ampatuan',
    'Datu Odin Sinsuat',
    'Datu Paglas',
    'Datu Piang',
    'Datu Salibo',
    'Datu Saudi-Ampatuan',
    'Datu Unsay',
    'General Salipada K. Pendatun',
    'Guindulungan',
    'Kabuntalan',
    'Mamasapano',
    'Mangudadatu',
    'Matanog',
    'Northern Kabuntalan',
    'Paglat',
    'Pandag',
    'Rajah Buayan',
    'Shariff Aguak',
    'Shariff Saydona Mustapha',
    'South Upi',
    'Sultan Mastura',
    'Sultan sa Barongis',
    'Talayan',
    'Upi',
  ],
  'Marinduque': [
    'Boac',
    'Buenavista',
    'Gasan',
    'Mogpog',
    'Santa Cruz',
    'Torrijos',
  ],
  'Masbate': [
    'Masbate City',
    'Aroroy',
    'Baleno',
    'Balud',
    'Batuan',
    'Cataingan',
    'Cawayan',
    'Claveria',
    'Dimasalang',
    'Esperanza',
    'Mandaon',
    'Milagros',
    'Mobo',
    'Monreal',
    'Palanas',
    'Pio V. Corpuz',
    'Placer',
    'San Fernando',
    'San Jacinto',
    'San Pascual',
    'Uson',
  ],
  'Mindoro Occidental': [
    'Mamburao',
    'Abra de Ilog',
    'Calintaan',
    'Looc',
    'Lubang',
    'Magsaysay',
    'Paluan',
    'Rizal',
    'Sablayan',
    'San Jose',
    'Santa Cruz',
  ],
  'Mindoro Oriental': [
    'Calapan City',
    'Baco',
    'Bansud',
    'Bongabong',
    'Bulalacao',
    'Gloria',
    'Mansalay',
    'Naujan',
    'Pinamalayan',
    'Pola',
    'Puerto Galera',
    'Roxas',
    'San Teodoro',
    'Socorro',
    'Victoria',
  ],
  'Misamis Occidental': [
    'Oroquieta City',
    'Ozamiz City',
    'Tangub City',
    'Aloran',
    'Baliangao',
    'Bonifacio',
    'Calamba',
    'Clarin',
    'Concepcion',
    'Don Victoriano Chiongbian',
    'Jimenez',
    'Lopez Jaena',
    'Panaon',
    'Plaridel',
    'Sapang Dalaga',
    'Sinacaban',
    'Tudela',
  ],
  'Misamis Oriental': [
    'Cagayan de Oro City',
    'Gingoog City',
    'Alubijid',
    'Balingasag',
    'Balingoan',
    'Binuangan',
    'Claveria',
    'El Salvador City',
    'Gitagum',
    'Initao',
    'Jasaan',
    'Kinoguitan',
    'Lagonglong',
    'Laguindingan',
    'Libertad',
    'Lugait',
    'Magsaysay',
    'Manticao',
    'Medina',
    'Naawan',
    'Opol',
    'Salay',
    'Sugbongcogon',
    'Tagoloan',
    'Talisayan',
    'Villanueva',
  ],
  'Mountain Province': [
    'Bontoc',
    'Barlig',
    'Bauko',
    'Besao',
    'Natonin',
    'Paracelis',
    'Sabangan',
    'Sadanga',
    'Sagada',
    'Tadian',
  ],
  'Negros Occidental': [
    'Bacolod City',
    'Bago City',
    'Cadiz City',
    'Escalante City',
    'Himamaylan City',
    'Kabankalan City',
    'La Carlota City',
    'Sagay City',
    'San Carlos City',
    'Silay City',
    'Sipalay City',
    'Talisay City',
    'Victorias City',
    'Binalbagan',
    'Calatrava',
    'Candoni',
    'Cauayan',
    'Enrique B. Magalona',
    'Hinigaran',
    'Hinoba-an',
    'Ilog',
    'Isabela',
    'La Castellana',
    'Manapla',
    'Moises Padilla',
    'Murcia',
    'Pontevedra',
    'Pulupandan',
    'Salvador Benedicto',
    'San Enrique',
    'Toboso',
    'Valladolid',
  ],
  'Negros Oriental': [
    'Dumaguete City',
    'Bais City',
    'Bayawan City',
    'Canlaon City',
    'Guihulngan City',
    'Tanjay City',
    'Amlan',
    'Ayungon',
    'Bacong',
    'Basay',
    'Bindoy',
    'Dauin',
    'Jimalalud',
    'La Libertad',
    'Mabinay',
    'Manjuyod',
    'Pamplona',
    'San Jose',
    'Santa Catalina',
    'Siaton',
    'Sibulan',
    'Tayasan',
    'Valencia',
    'Vallehermoso',
    'Zamboanguita',
  ],
  'Northern Samar': [
    'Catarman',
    'Allen',
    'Biri',
    'Bobon',
    'Capul',
    'Catubig',
    'Gamay',
    'Laoang',
    'Lapinig',
    'Las Navas',
    'Lavezares',
    'Lope de Vega',
    'Mapanas',
    'Mondragon',
    'Palapag',
    'Pambujan',
    'Rosario',
    'San Antonio',
    'San Isidro',
    'San Jose',
    'San Roque',
    'San Vicente',
    'Silvino Lubos',
    'Victoria',
  ],
  'Nueva Ecija': [
    'Cabanatuan City',
    'Gapan City',
    'Muñoz City',
    'Palayan City',
    'Science City of Muñoz',
    'Aliaga',
    'Bongabon',
    'Cabiao',
    'Carranglan',
    'Cuyapo',
    'Gabaldon',
    'General Mamerto Natividad',
    'General Tinio',
    'Guimba',
    'Jaen',
    'Laur',
    'Licab',
    'Llanera',
    'Lupao',
    'Nampicuan',
    'Pantabangan',
    'Peñaranda',
    'Quezon',
    'Rizal',
    'San Antonio',
    'San Isidro',
    'San Jose City',
    'San Leonardo',
    'Santa Rosa',
    'Santo Domingo',
    'Talavera',
    'Talugtug',
    'Zaragoza',
  ],
  'Nueva Vizcaya': [
    'Bayombong',
    'Aritao',
    'Bagabag',
    'Bambang',
    'Diadi',
    'Dupax del Norte',
    'Dupax del Sur',
    'Kasibu',
    'Kayapa',
    'Quezon',
    'Santa Fe',
    'Solano',
    'Villaverde',
  ],
  'Palawan': [
    'Puerto Princesa City',
    'Aborlan',
    'Agutaya',
    'Araceli',
    'Balabac',
    'Bataraza',
    "Brooke's Point",
    'Busuanga',
    'Cagayancillo',
    'Coron',
    'Culion',
    'Cuyo',
    'Dumaran',
    'El Nido',
    'Española',
    'Kalayaan',
    'Linapacan',
    'Magsaysay',
    'Narra',
    'Quezon',
    'Rizal',
    'Roxas',
    'San Vicente',
    'Sofronio Española',
    'Taytay',
  ],
  'Pampanga': [
    'Angeles City',
    'San Fernando City',
    'Apalit',
    'Arayat',
    'Bacolor',
    'Candaba',
    'Floridablanca',
    'Guagua',
    'Lubao',
    'Mabalacat City',
    'Macabebe',
    'Magalang',
    'Masantol',
    'Mexico',
    'Minalin',
    'Porac',
    'San Luis',
    'San Simon',
    'Santa Ana',
    'Santa Rita',
    'Santo Tomas',
    'Sasmuan',
  ],
  'Pangasinan': [
    'Dagupan City',
    'San Carlos City',
    'Urdaneta City',
    'Agno',
    'Aguilar',
    'Alaminos City',
    'Alcala',
    'Anda',
    'Asingan',
    'Balungao',
    'Bani',
    'Basista',
    'Bautista',
    'Bayambang',
    'Binalonan',
    'Binmaley',
    'Bugallon',
    'Burgos',
    'Calasiao',
    'Dasol',
    'Infanta',
    'Labrador',
    'Laoac',
    'Lingayen',
    'Mabini',
    'Malasiqui',
    'Manaoag',
    'Mangaldan',
    'Mangatarem',
    'Mapandan',
    'Natividad',
    'Pozorrubio',
    'Rosales',
    'San Fabian',
    'San Jacinto',
    'San Manuel',
    'San Nicolas',
    'San Quintin',
    'Santa Barbara',
    'Santa Maria',
    'Santo Tomas',
    'Sison',
    'Sual',
    'Tayug',
    'Umingan',
    'Urbiztondo',
    'Villasis',
  ],
  'Quezon': [
    'Lucena City',
    'Tayabas City',
    'Agdangan',
    'Alabat',
    'Atimonan',
    'Buenavista',
    'Burdeos',
    'Calauag',
    'Candelaria',
    'Catanauan',
    'General Luna',
    'General Nakar',
    'Guinayangan',
    'Gumaca',
    'Infanta',
    'Jomalig',
    'Lopez',
    'Lucban',
    'Macalelon',
    'Mauban',
    'Mulanay',
    'Padre Burgos',
    'Pagbilao',
    'Panukulan',
    'Patnanungan',
    'Perez',
    'Pitogo',
    'Plaridel',
    'Polillo',
    'Quezon',
    'Real',
    'Sampaloc',
    'San Andres',
    'San Antonio',
    'San Francisco',
    'San Narciso',
    'Sariaya',
    'Tagkawayan',
    'Tiaong',
    'Unisan',
  ],
  'Quirino': [
    'Cabarroguis',
    'Aglipay',
    'Diffun',
    'Maddela',
    'Nagtipunan',
    'Saguday',
  ],
  'Rizal': [
    'Antipolo City',
    'Angono',
    'Baras',
    'Binangonan',
    'Cainta',
    'Cardona',
    'Jalajala',
    'Morong',
    'Pililla',
    'Rodriguez',
    'San Mateo',
    'Tanay',
    'Taytay',
    'Teresa',
  ],
  'Romblon': [
    'Romblon',
    'Alcantara',
    'Banton',
    'Cajidiocan',
    'Calatrava',
    'Concepcion',
    'Corcuera',
    'Ferrol',
    'Looc',
    'Magdiwang',
    'Odiongan',
    'San Agustin',
    'San Andres',
    'San Fernando',
    'San Jose',
    'Santa Fe',
    'Santa Maria',
  ],
  'Samar': [
    'Catbalogan City',
    'Calbayog City',
    'Almagro',
    'Basey',
    'Calbiga',
    'Daram',
    'Gandara',
    'Hinabangan',
    'Jiabong',
    'Marabut',
    'Matuguinao',
    'Motiong',
    'Pinabacdao',
    'San Jorge',
    'San Jose de Buan',
    'San Sebastian',
    'Santa Rita',
    'Santo Niño',
    'Tagapul-an',
    'Talalora',
    'Tarangnan',
    'Villareal',
    'Zumarraga',
  ],
  'Sarangani': [
    'Alabel',
    'Glan',
    'Kiamba',
    'Maasim',
    'Maitum',
    'Malapatan',
    'Malungon',
  ],
  'Siquijor': [
    'Siquijor',
    'Enrique Villanueva',
    'Larena',
    'Lazi',
    'Maria',
    'San Juan',
  ],
  'Sorsogon': [
    'Sorsogon City',
    'Barcelona',
    'Bulan',
    'Bulusan',
    'Casiguran',
    'Castilla',
    'Donsol',
    'Gubat',
    'Irosin',
    'Juban',
    'Magallanes',
    'Matnog',
    'Pilar',
    'Prieto Diaz',
    'Santa Magdalena',
  ],
  'South Cotabato': [
    'General Santos City',
    'Koronadal City',
    'Banga',
    'Lake Sebu',
    'Norala',
    'Polomolok',
    'Santo Niño',
    'Surallah',
    "T'boli",
    'Tampakan',
    'Tantangan',
    'Tupi',
  ],
  'Southern Leyte': [
    'Maasin City',
    'Anahawan',
    'Bontoc',
    'Hinunangan',
    'Hinundayan',
    'Libagon',
    'Liloan',
    'Limasawa',
    'Macrohon',
    'Malitbog',
    'Padre Burgos',
    'Pintuyan',
    'Saint Bernard',
    'San Francisco',
    'San Juan',
    'San Ricardo',
    'Silago',
    'Sogod',
    'Tomas Oppus',
  ],
  'Sultan Kudarat': [
    'Isulan',
    'Tacurong City',
    'Bagumbayan',
    'Columbio',
    'Esperanza',
    'Kalamansig',
    'Lambayong',
    'Lebak',
    'Lutayan',
    'Palimbang',
    'President Quirino',
    'Senator Ninoy Aquino',
  ],
  'Sulu': [
    'Jolo',
    'Banguingui',
    'Hadji Panglima Tahil',
    'Indanan',
    'Kalingalan Caluang',
    'Lugus',
    'Luuk',
    'Maimbung',
    'Old Panamao',
    'Omar',
    'Pandami',
    'Panglima Estino',
    'Pangutaran',
    'Parang',
    'Pata',
    'Patikul',
    'Siasi',
    'Talipao',
    'Tapul',
    'Tongkil',
  ],
  'Surigao del Norte': [
    'Surigao City',
    'Bislig City',
    'Alegria',
    'Bacuag',
    'Burgos',
    'Claver',
    'Dapa',
    'Del Carmen',
    'General Luna',
    'Gigaquit',
    'Mainit',
    'Malimono',
    'Pilar',
    'Placer',
    'San Benito',
    'San Francisco',
    'San Isidro',
    'Santa Monica',
    'Sison',
    'Socorro',
    'Tagana-an',
    'Tubod',
  ],
  'Surigao del Sur': [
    'Tandag City',
    'Bislig City',
    'Barobo',
    'Bayabas',
    'Cagwait',
    'Cantilan',
    'Carmen',
    'Carrascal',
    'Cortes',
    'Hinatuan',
    'Lanuza',
    'Lianga',
    'Lingig',
    'Madrid',
    'Marihatag',
    'San Agustin',
    'San Miguel',
    'Santa Maria',
    'Tagbina',
    'Tago',
    'Tubod',
  ],
  'Tarlac': [
    'Tarlac City',
    'Anao',
    'Bamban',
    'Camiling',
    'Capas',
    'Concepcion',
    'Gerona',
    'La Paz',
    'Mayantoc',
    'Moncada',
    'Paniqui',
    'Pura',
    'Ramos',
    'San Clemente',
    'San Jose',
    'San Manuel',
    'Santa Ignacia',
    'Victoria',
  ],
  'Tawi-Tawi': [
    'Bongao',
    'Languyan',
    'Mapun',
    'Panglima Sugala',
    'Sapa-Sapa',
    'Sibutu',
    'Simunul',
    'Sitangkai',
    'South Ubian',
    'Tandubas',
    'Turtle Islands',
  ],
  'Zambales': [
    'Olongapo City',
    'Botolan',
    'Cabangan',
    'Candelaria',
    'Castillejos',
    'Iba',
    'Masinloc',
    'Palauig',
    'San Antonio',
    'San Felipe',
    'San Marcelino',
    'San Narciso',
    'Santa Cruz',
    'Subic',
  ],
  'Zamboanga del Norte': [
    'Dipolog City',
    'Dapitan City',
    'Baliguian',
    'Godod',
    'Gutalac',
    'Jose Dalman',
    'Kalawit',
    'Katipunan',
    'La Libertad',
    'Labason',
    'Leon B. Postigo',
    'Liloy',
    'Manukan',
    'Mutia',
    'Piñan',
    'Polanco',
    'President Manuel A. Roxas',
    'Rizal',
    'Salug',
    'San Miguel',
    'Sergio Osmeña Sr.',
    'Siayan',
    'Sibuco',
    'Sibutad',
    'Sindangan',
    'Siocon',
    'Sirawai',
    'Tampilisan',
  ],
  'Zamboanga del Sur': [
    'Pagadian City',
    'Zamboanga City',
    'Aurora',
    'Bayog',
    'Dimataling',
    'Dinas',
    'Dumalinao',
    'Dumingag',
    'Guipos',
    'Josefina',
    'Kumalarang',
    'Labangan',
    'Lakewood',
    'Lapuyan',
    'Mahayag',
    'Margosatubig',
    'Midsalip',
    'Molave',
    'Pitogo',
    'Ramon Magsaysay',
    'San Miguel',
    'San Pablo',
    'Sominot',
    'Tabina',
    'Tambulig',
    'Tigbao',
    'Tukuran',
    'Vincenzo A. Sagun',
  ],
  'Zamboanga Sibugay': [
    'Ipil',
    'Alicia',
    'Buug',
    'Diplahan',
    'Imelda',
    'Kabasalan',
    'Mabuhay',
    'Malangas',
    'Naga',
    'Olutanga',
    'Payao',
    'Ramon Magsaysay',
    'Roseller T. Lim',
    'Siay',
    'Talusan',
    'Titay',
    'Tungawan',
  ],
};

// ─── Register Screen ──────────────────────────────────────────────────────────

class RegisterScreen extends StatefulWidget {
  const RegisterScreen({super.key});

  @override
  State<RegisterScreen> createState() => _RegisterScreenState();
}

class _RegisterScreenState extends State<RegisterScreen>
    with TickerProviderStateMixin {
  final _formKey = GlobalKey<FormState>();
  final _firstNameCtrl = TextEditingController();
  final _lastNameCtrl = TextEditingController();
  final _emailCtrl = TextEditingController();
  final _phoneCtrl = TextEditingController();
  final _passwordCtrl = TextEditingController();
  final _confirmPasswordCtrl = TextEditingController();
  final _agencyNameCtrl = TextEditingController();
  final _badgeNumberCtrl = TextEditingController();
  final _streetCtrl = TextEditingController();
  final _zipCtrl = TextEditingController();

  String _selectedRole = 'citizen';
  String _selectedGender = 'Male';
  String? _selectedProvince;
  String? _selectedCity;
  bool _showPassword = false;
  bool _showConfirmPassword = false;
  bool _isLoading = false;
  File? _govIdFile;

  late final AnimationController _rescuerFieldsController;
  late final Animation<double> _rescuerFieldsAnimation;

  static const _primaryBlue = Color(0xFF0D47A1);
  static const _dangerRed = Color(0xFFD7263D);
  static const _successGreen = Color(0xFF1FAA59);
  static const _background = Color(0xFFF5F7FA);
  static const _textSecondary = Color(0xFF546E7A);

  @override
  void initState() {
    super.initState();
    _rescuerFieldsController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 350),
    );
    _rescuerFieldsAnimation = CurvedAnimation(
      parent: _rescuerFieldsController,
      curve: Curves.easeInOut,
    );
  }

  @override
  void dispose() {
    _rescuerFieldsController.dispose();
    for (final c in [
      _firstNameCtrl,
      _lastNameCtrl,
      _emailCtrl,
      _phoneCtrl,
      _passwordCtrl,
      _confirmPasswordCtrl,
      _agencyNameCtrl,
      _badgeNumberCtrl,
      _streetCtrl,
      _zipCtrl,
    ]) {
      c.dispose();
    }
    super.dispose();
  }

  void _selectRole(String role) {
    if (_selectedRole == role || _isLoading) return;
    setState(() => _selectedRole = role);
    if (role == 'rescuer') {
      _rescuerFieldsController.forward();
    } else {
      _rescuerFieldsController.reverse();
    }
  }

  Future<void> _pickGovId(ImageSource source) async {
    if (_isLoading) return;
    try {
      final picker = ImagePicker();
      final picked = await picker.pickImage(source: source, imageQuality: 85);
      if (picked != null && mounted) {
        setState(() => _govIdFile = File(picked.path));
      }
    } catch (_) {
      _showSnack(
        'Could not access ${source == ImageSource.camera ? 'camera' : 'gallery'}. Check permissions.',
        isError: true,
      );
    }
  }

  void _showGovIdOptions() {
    showModalBottomSheet(
      context: context,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (_) => SafeArea(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const SizedBox(height: 12),
            Container(
              width: 40,
              height: 4,
              decoration: BoxDecoration(
                color: Colors.grey[300],
                borderRadius: BorderRadius.circular(2),
              ),
            ),
            const SizedBox(height: 16),
            const Text(
              'Upload Government ID',
              style: TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.w700,
                color: Color(0xFF263238),
              ),
            ),
            const SizedBox(height: 8),
            ListTile(
              leading: Container(
                padding: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  color: _primaryBlue.withAlpha(25),
                  borderRadius: BorderRadius.circular(10),
                ),
                child: const Icon(
                  Icons.camera_alt_outlined,
                  color: _primaryBlue,
                ),
              ),
              title: const Text('Take a Photo'),
              subtitle: const Text('Scan your ID using camera'),
              onTap: () {
                Navigator.pop(context);
                _pickGovId(ImageSource.camera);
              },
            ),
            ListTile(
              leading: Container(
                padding: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  color: _primaryBlue.withAlpha(25),
                  borderRadius: BorderRadius.circular(10),
                ),
                child: const Icon(
                  Icons.photo_library_outlined,
                  color: _primaryBlue,
                ),
              ),
              title: const Text('Choose from Gallery'),
              subtitle: const Text('Select an existing photo'),
              onTap: () {
                Navigator.pop(context);
                _pickGovId(ImageSource.gallery);
              },
            ),
            if (_govIdFile != null)
              ListTile(
                leading: Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: _dangerRed.withAlpha(25),
                    borderRadius: BorderRadius.circular(10),
                  ),
                  child: const Icon(Icons.delete_outline, color: _dangerRed),
                ),
                title: const Text(
                  'Remove Photo',
                  style: TextStyle(color: _dangerRed),
                ),
                onTap: () {
                  Navigator.pop(context);
                  setState(() => _govIdFile = null);
                },
              ),
            const SizedBox(height: 16),
          ],
        ),
      ),
    );
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;

    if (_selectedProvince == null) {
      _showSnack('Please select a province.', isError: true);
      return;
    }
    if (_selectedCity == null) {
      _showSnack('Please select a city/municipality.', isError: true);
      return;
    }
    if (_govIdFile == null) {
      _showSnack('Please upload a Government ID.', isError: true);
      return;
    }

    setState(() => _isLoading = true);

    try {
      final email = _emailCtrl.text.trim();

      final methods = await FirebaseAuth.instance.fetchSignInMethodsForEmail(
        email,
      );
      if (methods.isNotEmpty) {
        if (mounted) {
          _showSnack(
            'An account with this email already exists.',
            isError: true,
          );
        }
        return;
      }

      await OtpHelper.generateAndSend(
        email: email,
        purpose: OtpPurpose.registration,
      );

      final pendingData = PendingRegistrationData(
        email: email,
        password: _passwordCtrl.text,
        firstName: _firstNameCtrl.text.trim(),
        lastName: _lastNameCtrl.text.trim(),
        phone: _phoneCtrl.text.trim(),
        gender: _selectedGender,
        street: _streetCtrl.text.trim(),
        city: _selectedCity!,
        province: _selectedProvince!,
        zip: _zipCtrl.text.trim(),
        role: _selectedRole,
        govIdFile: _govIdFile,
        agencyName: _selectedRole == 'rescuer'
            ? _agencyNameCtrl.text.trim()
            : null,
        badgeNumber: _selectedRole == 'rescuer'
            ? _badgeNumberCtrl.text.trim()
            : null,
      );

      if (mounted) {
        Navigator.pushAndRemoveUntil(
          context,
          MaterialPageRoute(
            builder: (_) => OtpVerificationScreen(
              email: email,
              purpose: OtpPurpose.registration,
              pendingRegistration: pendingData,
            ),
          ),
          (route) => false,
        );
      }
    } on FirebaseAuthException catch (e) {
      if (mounted) _showAuthError(e);
    } catch (e) {
      if (mounted) {
        _showSnack('Something went wrong. Please try again.', isError: true);
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  void _showAuthError(FirebaseAuthException e) {
    final msg = switch (e.code) {
      'email-already-in-use' => 'An account with this email already exists.',
      'invalid-email' => 'Please enter a valid email address.',
      'weak-password' => 'Password is too weak. Use at least 6 characters.',
      _ => 'Registration failed: ${e.message ?? e.code}',
    };
    _showSnack(msg, isError: true);
  }

  void _showSnack(String msg, {bool isError = false}) {
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Row(
          children: [
            Icon(
              isError ? Icons.error_outline : Icons.check_circle_outline,
              color: Colors.white,
              size: 18,
            ),
            const SizedBox(width: 10),
            Expanded(child: Text(msg)),
          ],
        ),
        backgroundColor: isError ? _dangerRed : _successGreen,
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
        margin: const EdgeInsets.fromLTRB(16, 0, 16, 16),
        duration: const Duration(seconds: 4),
      ),
    );
  }

  // ─── Build ────────────────────────────────────────────────────────────────────

  @override
  Widget build(BuildContext context) {
    return LoadingOverlay(
      isLoading: _isLoading,
      child: Scaffold(
        backgroundColor: _background,
        body: SafeArea(
          child: CustomScrollView(
            slivers: [
              SliverToBoxAdapter(child: _buildHeader()),
              SliverPadding(
                padding: const EdgeInsets.fromLTRB(24, 24, 24, 32),
                sliver: SliverToBoxAdapter(
                  child: Form(
                    key: _formKey,
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      children: [
                        // ── Personal Info ─────────────────────────────────
                        _sectionLabel('Personal Information'),
                        const SizedBox(height: 12),
                        Row(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Expanded(
                              child: _buildField(
                                controller: _firstNameCtrl,
                                label: 'First Name',
                                icon: Icons.person_outline,
                                textCapitalization: TextCapitalization.words,
                                validator: (v) =>
                                    v!.trim().isEmpty ? 'Required' : null,
                              ),
                            ),
                            const SizedBox(width: 16),
                            Expanded(
                              child: _buildField(
                                controller: _lastNameCtrl,
                                label: 'Last Name',
                                icon: Icons.person_outline,
                                textCapitalization: TextCapitalization.words,
                                validator: (v) =>
                                    v!.trim().isEmpty ? 'Required' : null,
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 16),

                        _buildGenderSelector(),
                        const SizedBox(height: 16),

                        _buildField(
                          controller: _emailCtrl,
                          label: 'Email Address',
                          icon: Icons.email_outlined,
                          keyboardType: TextInputType.emailAddress,
                          validator: (v) {
                            if (v == null || v.trim().isEmpty)
                              return 'Required';
                            if (!RegExp(
                              r'^[^@]+@[^@]+\.[^@]+',
                            ).hasMatch(v.trim())) {
                              return 'Enter a valid email';
                            }
                            return null;
                          },
                        ),
                        const SizedBox(height: 16),
                        _buildField(
                          controller: _phoneCtrl,
                          label: 'Phone Number (09XXXXXXXXX)',
                          icon: Icons.phone_outlined,
                          keyboardType: TextInputType.phone,
                          inputFormatters: [
                            FilteringTextInputFormatter.allow(RegExp(r'[\d+]')),
                            LengthLimitingTextInputFormatter(13),
                          ],
                          validator: (v) {
                            if (v == null || v.trim().isEmpty)
                              return 'Required';
                            final cleaned = v.trim().replaceAll(
                              RegExp(r'\s+'),
                              '',
                            );
                            if (!RegExp(
                              r'^(09|\+639|9)\d{9}$',
                            ).hasMatch(cleaned)) {
                              return 'Enter a valid PH number';
                            }
                            return null;
                          },
                        ),
                        const SizedBox(height: 24),

                        // ── Address ───────────────────────────────────────
                        _sectionLabel('Address'),
                        const SizedBox(height: 12),
                        _buildField(
                          controller: _streetCtrl,
                          label: 'Street / Barangay',
                          icon: Icons.home_outlined,
                          textCapitalization: TextCapitalization.words,
                          validator: (v) =>
                              v!.trim().isEmpty ? 'Required' : null,
                        ),
                        const SizedBox(height: 16),

                        // Province dropdown
                        _buildDropdownField(
                          label: 'Province',
                          icon: Icons.map_outlined,
                          value: _selectedProvince,
                          hint: 'Select Province',
                          items: _phProvinceCities.keys.toList()..sort(),
                          onChanged: (v) => setState(() {
                            _selectedProvince = v;
                            _selectedCity = null;
                          }),
                        ),
                        const SizedBox(height: 16),

                        // City dropdown
                        _buildDropdownField(
                          label: 'City / Municipality',
                          icon: Icons.location_city_outlined,
                          value: _selectedCity,
                          hint: _selectedProvince == null
                              ? 'Select Province first'
                              : 'Select City / Municipality',
                          items: _selectedProvince != null
                              ? (_phProvinceCities[_selectedProvince!] ?? [])
                              : [],
                          onChanged: _selectedProvince == null
                              ? null
                              : (v) => setState(() => _selectedCity = v),
                          isDisabled: _selectedProvince == null,
                        ),
                        const SizedBox(height: 16),

                        SizedBox(
                          width: 140,
                          child: _buildField(
                            controller: _zipCtrl,
                            label: 'ZIP Code',
                            icon: Icons.markunread_mailbox_outlined,
                            keyboardType: TextInputType.number,
                            inputFormatters: [
                              FilteringTextInputFormatter.digitsOnly,
                              LengthLimitingTextInputFormatter(4),
                            ],
                            validator: (v) {
                              if (v == null || v.trim().isEmpty)
                                return 'Required';
                              if (v.length < 4)
                                return 'Enter a valid 4-digit ZIP';
                              return null;
                            },
                          ),
                        ),
                        const SizedBox(height: 24),

                        // ── Security ──────────────────────────────────────
                        _sectionLabel('Security'),
                        const SizedBox(height: 12),
                        _buildField(
                          controller: _passwordCtrl,
                          label: 'Password',
                          icon: Icons.lock_outline,
                          obscureText: !_showPassword,
                          validator: (v) {
                            if (v == null || v.isEmpty) return 'Required';
                            if (v.length < 6) return 'Minimum 6 characters';
                            return null;
                          },
                          suffixIcon: IconButton(
                            icon: Icon(
                              _showPassword
                                  ? Icons.visibility_off_outlined
                                  : Icons.visibility_outlined,
                              color: const Color(0xFF90A4AE),
                              size: 20,
                            ),
                            onPressed: () =>
                                setState(() => _showPassword = !_showPassword),
                          ),
                        ),
                        const SizedBox(height: 16),
                        _buildField(
                          controller: _confirmPasswordCtrl,
                          label: 'Confirm Password',
                          icon: Icons.lock_outline,
                          obscureText: !_showConfirmPassword,
                          validator: (v) {
                            if (v == null || v.isEmpty) return 'Required';
                            if (v != _passwordCtrl.text)
                              return 'Passwords do not match';
                            return null;
                          },
                          suffixIcon: IconButton(
                            icon: Icon(
                              _showConfirmPassword
                                  ? Icons.visibility_off_outlined
                                  : Icons.visibility_outlined,
                              color: const Color(0xFF90A4AE),
                              size: 20,
                            ),
                            onPressed: () => setState(
                              () =>
                                  _showConfirmPassword = !_showConfirmPassword,
                            ),
                          ),
                        ),
                        const SizedBox(height: 24),

                        // ── Role ──────────────────────────────────────────
                        _sectionLabel('I am registering as'),
                        const SizedBox(height: 12),
                        _buildRoleSelector(),

                        // ── Gov ID ────────────────────────────────────────
                        const SizedBox(height: 16),
                        _buildGovIdUploader(),

                        // ── Rescuer-only fields ───────────────────────────
                        SizeTransition(
                          sizeFactor: _rescuerFieldsAnimation,
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.stretch,
                            children: [
                              const SizedBox(height: 16),
                              _buildField(
                                controller: _agencyNameCtrl,
                                label: 'Agency Name',
                                icon: Icons.business_outlined,
                              ),
                              const SizedBox(height: 16),
                              _buildField(
                                controller: _badgeNumberCtrl,
                                label: 'Badge Number',
                                icon: Icons.badge_outlined,
                              ),
                            ],
                          ),
                        ),

                        const SizedBox(height: 32),
                        SizedBox(
                          height: 56,
                          child: ElevatedButton(
                            onPressed: _isLoading ? null : _submit,
                            style: ElevatedButton.styleFrom(
                              backgroundColor: _primaryBlue,
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(14),
                              ),
                            ),
                            child: _isLoading
                                ? const SizedBox(
                                    width: 22,
                                    height: 22,
                                    child: CircularProgressIndicator(
                                      strokeWidth: 2.5,
                                      valueColor: AlwaysStoppedAnimation<Color>(
                                        Colors.white,
                                      ),
                                    ),
                                  )
                                : const Text(
                                    'Create Account',
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 16,
                                      fontWeight: FontWeight.w700,
                                    ),
                                  ),
                          ),
                        ),
                        const SizedBox(height: 20),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Text(
                              'Already have an account? ',
                              style: TextStyle(
                                color: _textSecondary,
                                fontSize: 14,
                              ),
                            ),
                            TextButton(
                              onPressed: _isLoading
                                  ? null
                                  : () => Navigator.pop(context),
                              style: TextButton.styleFrom(
                                foregroundColor: _primaryBlue,
                                padding: EdgeInsets.zero,
                                minimumSize: Size.zero,
                                tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                              ),
                              child: const Text(
                                'Sign In',
                                style: TextStyle(
                                  fontSize: 14,
                                  fontWeight: FontWeight.w700,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  // ─── UI Helpers ───────────────────────────────────────────────────────────────

  Widget _sectionLabel(String text) => Text(
    text,
    style: const TextStyle(
      fontSize: 15,
      fontWeight: FontWeight.w800,
      color: _primaryBlue,
    ),
  );

  Widget _buildHeader() => Container(
    padding: const EdgeInsets.fromLTRB(24, 24, 24, 24),
    color: _primaryBlue,
    child: Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        GestureDetector(
          onTap: () => Navigator.pop(context),
          child: Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: Colors.white.withAlpha(30),
              borderRadius: BorderRadius.circular(10),
            ),
            child: const Icon(Icons.arrow_back, color: Colors.white, size: 20),
          ),
        ),
        const SizedBox(height: 16),
        const Text(
          'Create Account',
          style: TextStyle(
            color: Colors.white,
            fontSize: 24,
            fontWeight: FontWeight.w800,
          ),
        ),
        const SizedBox(height: 4),
        const Text(
          'Join the ResQConnect network',
          style: TextStyle(color: Colors.white70, fontSize: 13),
        ),
      ],
    ),
  );

  Widget _buildGenderSelector() => Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      const Text(
        'Gender',
        style: TextStyle(
          fontSize: 13,
          fontWeight: FontWeight.w600,
          color: Color(0xFF37474F),
        ),
      ),
      const SizedBox(height: 10),
      Row(
        children: ['Male', 'Female', 'Other'].map((g) {
          final isSelected = _selectedGender == g;
          return Expanded(
            child: Padding(
              padding: EdgeInsets.only(right: g != 'Other' ? 10 : 0),
              child: GestureDetector(
                onTap: () => setState(() => _selectedGender = g),
                child: AnimatedContainer(
                  duration: const Duration(milliseconds: 200),
                  padding: const EdgeInsets.symmetric(vertical: 12),
                  decoration: BoxDecoration(
                    color: isSelected ? _primaryBlue : Colors.white,
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(
                      color: isSelected
                          ? _primaryBlue
                          : const Color(0xFFCFD8DC),
                      width: 1.5,
                    ),
                  ),
                  child: Text(
                    g,
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: isSelected
                          ? Colors.white
                          : const Color(0xFF37474F),
                      fontWeight: FontWeight.w600,
                      fontSize: 13,
                    ),
                  ),
                ),
              ),
            ),
          );
        }).toList(),
      ),
    ],
  );

  Widget _buildRoleSelector() => Row(
    children: [
      Expanded(child: _roleCard('citizen', 'Citizen', Icons.person_outline)),
      const SizedBox(width: 12),
      Expanded(child: _roleCard('rescuer', 'Rescuer', Icons.shield_outlined)),
    ],
  );

  Widget _roleCard(String role, String label, IconData icon) {
    final isSelected = _selectedRole == role;
    return GestureDetector(
      onTap: () => _selectRole(role),
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 200),
        padding: const EdgeInsets.symmetric(vertical: 14),
        decoration: BoxDecoration(
          color: isSelected ? _primaryBlue : Colors.white,
          borderRadius: BorderRadius.circular(12),
          border: Border.all(
            color: isSelected ? _primaryBlue : const Color(0xFFCFD8DC),
            width: 1.5,
          ),
        ),
        child: Column(
          children: [
            Icon(
              icon,
              color: isSelected ? Colors.white : const Color(0xFF546E7A),
              size: 22,
            ),
            const SizedBox(height: 6),
            Text(
              label,
              style: TextStyle(
                color: isSelected ? Colors.white : const Color(0xFF37474F),
                fontWeight: FontWeight.w700,
                fontSize: 14,
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildGovIdUploader() => Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      const Text(
        'Government ID',
        style: TextStyle(
          fontSize: 13,
          fontWeight: FontWeight.w600,
          color: Color(0xFF37474F),
        ),
      ),
      const SizedBox(height: 8),
      GestureDetector(
        onTap: _showGovIdOptions,
        child: AnimatedContainer(
          duration: const Duration(milliseconds: 200),
          width: double.infinity,
          height: _govIdFile != null ? 180 : 100,
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(12),
            border: Border.all(
              color: _govIdFile != null
                  ? _primaryBlue
                  : const Color(0xFFCFD8DC),
              width: _govIdFile != null ? 2 : 1.5,
            ),
          ),
          child: _govIdFile != null
              ? Stack(
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.circular(11),
                      child: Image.file(
                        _govIdFile!,
                        width: double.infinity,
                        height: double.infinity,
                        fit: BoxFit.cover,
                      ),
                    ),
                    Positioned(
                      top: 8,
                      right: 8,
                      child: GestureDetector(
                        onTap: _showGovIdOptions,
                        child: Container(
                          padding: const EdgeInsets.all(6),
                          decoration: BoxDecoration(
                            color: Colors.black.withAlpha(150),
                            borderRadius: BorderRadius.circular(8),
                          ),
                          child: const Row(
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              Icon(
                                Icons.edit_outlined,
                                color: Colors.white,
                                size: 14,
                              ),
                              SizedBox(width: 4),
                              Text(
                                'Change',
                                style: TextStyle(
                                  color: Colors.white,
                                  fontSize: 12,
                                  fontWeight: FontWeight.w600,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ),
                    Positioned(
                      bottom: 8,
                      left: 8,
                      child: Container(
                        padding: const EdgeInsets.symmetric(
                          horizontal: 8,
                          vertical: 4,
                        ),
                        decoration: BoxDecoration(
                          color: _successGreen,
                          borderRadius: BorderRadius.circular(6),
                        ),
                        child: const Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Icon(
                              Icons.check_circle,
                              color: Colors.white,
                              size: 12,
                            ),
                            SizedBox(width: 4),
                            Text(
                              'ID Uploaded',
                              style: TextStyle(
                                color: Colors.white,
                                fontSize: 11,
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ],
                )
              : Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(
                      Icons.credit_card_outlined,
                      color: _primaryBlue.withAlpha(180),
                      size: 32,
                    ),
                    const SizedBox(height: 8),
                    Text(
                      'Tap to upload Government ID',
                      style: TextStyle(
                        color: _primaryBlue.withAlpha(200),
                        fontSize: 13,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                    const SizedBox(height: 2),
                    const Text(
                      'Camera or Gallery',
                      style: TextStyle(color: Color(0xFF90A4AE), fontSize: 11),
                    ),
                  ],
                ),
        ),
      ),
    ],
  );

  Widget _buildDropdownField({
    required String label,
    required IconData icon,
    required String? value,
    required String hint,
    required List<String> items,
    required void Function(String?)? onChanged,
    bool isDisabled = false,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: const TextStyle(
            fontSize: 13,
            fontWeight: FontWeight.w600,
            color: Color(0xFF37474F),
          ),
        ),
        const SizedBox(height: 8),
        Container(
          decoration: BoxDecoration(
            color: isDisabled ? const Color(0xFFECEFF1) : Colors.white,
            borderRadius: BorderRadius.circular(12),
            border: Border.all(color: const Color(0xFFCFD8DC), width: 1),
          ),
          child: DropdownButtonHideUnderline(
            child: DropdownButton<String>(
              value: value,
              isExpanded: true,
              icon: const Icon(
                Icons.keyboard_arrow_down_rounded,
                color: Color(0xFF90A4AE),
              ),
              hint: Padding(
                padding: const EdgeInsets.only(left: 12),
                child: Row(
                  children: [
                    Icon(icon, size: 20, color: const Color(0xFF90A4AE)),
                    const SizedBox(width: 10),
                    Text(
                      hint,
                      style: const TextStyle(
                        color: Color(0xFFB0BEC5),
                        fontSize: 14,
                      ),
                    ),
                  ],
                ),
              ),
              padding: const EdgeInsets.symmetric(horizontal: 4),
              borderRadius: BorderRadius.circular(12),
              onChanged: onChanged,
              selectedItemBuilder: (ctx) => items
                  .map(
                    (e) => Padding(
                      padding: const EdgeInsets.only(left: 12),
                      child: Row(
                        children: [
                          Icon(icon, size: 20, color: const Color(0xFF90A4AE)),
                          const SizedBox(width: 10),
                          Expanded(
                            child: Text(
                              e,
                              style: const TextStyle(fontSize: 14),
                              overflow: TextOverflow.ellipsis,
                            ),
                          ),
                        ],
                      ),
                    ),
                  )
                  .toList(),
              items: items
                  .map((e) => DropdownMenuItem(value: e, child: Text(e)))
                  .toList(),
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildField({
    required TextEditingController controller,
    required String label,
    required IconData icon,
    bool obscureText = false,
    TextInputType keyboardType = TextInputType.text,
    TextCapitalization textCapitalization = TextCapitalization.none,
    List<TextInputFormatter>? inputFormatters,
    String? Function(String?)? validator,
    Widget? suffixIcon,
  }) {
    return TextFormField(
      controller: controller,
      obscureText: obscureText,
      keyboardType: keyboardType,
      textCapitalization: textCapitalization,
      inputFormatters: inputFormatters,
      validator: validator,
      style: const TextStyle(fontSize: 15),
      decoration: InputDecoration(
        labelText: label,
        prefixIcon: Icon(icon, size: 20, color: const Color(0xFF90A4AE)),
        suffixIcon: suffixIcon,
        filled: true,
        fillColor: Colors.white,
        contentPadding: const EdgeInsets.symmetric(
          horizontal: 16,
          vertical: 14,
        ),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: const BorderSide(color: Color(0xFFCFD8DC), width: 1),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: const BorderSide(color: Color(0xFFCFD8DC), width: 1),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: const BorderSide(color: _primaryBlue, width: 1.8),
        ),
        errorBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: const BorderSide(color: _dangerRed, width: 1.5),
        ),
        focusedErrorBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: const BorderSide(color: _dangerRed, width: 1.8),
        ),
      ),
    );
  }
}
